default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: lead_manager_development

test:
  <<: *default
  database: lead_manager_test

production:
  <<: *default
  database: lead_manager_production